# Generated by Django 4.1.3 on 2022-11-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_train_booked_by_remove_train_status_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
